# Generated by Django 6.0.1 on 2026-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('naped', models.IntegerField(choices=[(1, 'Na przednie koła'), (2, 'Na tylne koła'), (3, '4x4')], default=1)),
            ],
        ),
    ]
