# Generated by Django 6.0.1 on 2026-01-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='paliwo',
            field=models.IntegerField(choices=[(1, 'Diesel'), (2, 'Benzyna'), (3, 'Elektryczny'), (4, 'Hybrydowy')], default=2),
        ),
        migrations.AddField(
            model_name='samochod',
            name='przekładnia',
            field=models.IntegerField(choices=[(1, 'Manual'), (2, 'Automat')], default=1),
        ),
    ]
