# Generated by Django 6.0.1 on 2026-01-27 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0002_samochod_paliwo_samochod_przekładnia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samochod',
            old_name='naped',
            new_name='napęd',
        ),
        migrations.AddField(
            model_name='samochod',
            name='rok_produkcji',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2026)], verbose_name='Rok Prokukcji'),
            preserve_default=False,
        ),
    ]
