# Generated by Django 6.0.1 on 2026-01-27 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0003_rename_naped_samochod_napęd_samochod_rok_produkcji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochod',
            name='rok_produkcji',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2026)], verbose_name='Rok Prokukcji'),
        ),
    ]
