# Generated by Django 6.0.1 on 2026-01-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0004_alter_samochod_rok_produkcji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samochod',
            options={'verbose_name': 'Samochód', 'verbose_name_plural': 'Samochody'},
        ),
    ]
