# Generated by Django 6.0.1 on 2026-01-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0005_alter_samochod_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.AlterField(
            model_name='samochod',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplikacjawypozyczalnia.marka', verbose_name='Marka'),
        ),
    ]
