# Generated by Django 6.0.1 on 2026-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0006_marka_alter_samochod_marka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Marka',
            },
        ),
        migrations.AlterModelOptions(
            name='marka',
            options={'verbose_name': 'Marka'},
        ),
    ]
