# Generated by Django 6.0.1 on 2026-01-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0007_model_alter_marka_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marka',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Marki'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Modele'},
        ),
    ]
