# Generated by Django 6.0.1 on 2026-01-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0008_alter_marka_options_alter_model_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='moc',
            field=models.PositiveIntegerField(null=True, verbose_name='Moc (KM)'),
        ),
        migrations.AddField(
            model_name='samochod',
            name='pojemnosc',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='Pojemność (cm3)'),
        ),
        migrations.AddField(
            model_name='samochod',
            name='przyspieszenie',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='0-100 km/h (s)'),
        ),
    ]
