# Generated by Django 6.0.1 on 2026-01-27 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0009_samochod_moc_samochod_pojemnosc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochod',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplikacjawypozyczalnia.model', verbose_name='Model'),
        ),
    ]
