# Generated by Django 6.0.1 on 2026-01-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0010_alter_samochod_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='marka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacjawypozyczalnia.marka', verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='samochod',
            name='rejestracja',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='samochod',
            name='vin',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='nazwa',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nazwa modelu'),
        ),
    ]
