# Generated by Django 6.0.1 on 2026-01-29 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0011_model_marka_samochod_rejestracja_samochod_vin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True, verbose_name='Nazwa modelu')),
                ('marka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacjawypozyczalnia.marka', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modele',
            },
        ),
        migrations.AlterField(
            model_name='samochod',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplikacjawypozyczalnia.modelauta', verbose_name='Model'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
