# Generated by Django 6.0.1 on 2026-01-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0012_modelauta_alter_samochod_model_delete_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('instrukcja', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Statusy',
            },
        ),
        migrations.AlterModelOptions(
            name='marka',
            options={'ordering': ['nazwa'], 'verbose_name': 'Marka', 'verbose_name_plural': 'Marki'},
        ),
    ]
