# Generated by Django 6.0.1 on 2026-01-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0013_status_alter_marka_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['nazwa'], 'verbose_name_plural': 'Statusy'},
        ),
    ]
