# Generated by Django 6.0.1 on 2026-01-29 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0015_klient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ['nazwisko'], 'verbose_name_plural': 'Klienci'},
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypo', models.DateField()),
                ('data_zwrotu', models.DateField()),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjawypozyczalnia.samochod')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacjawypozyczalnia.klient')),
            ],
            options={
                'verbose_name_plural': 'Wypożyczenia',
                'ordering': ['data_wypo'],
            },
        ),
    ]
