# Generated by Django 6.0.1 on 2026-01-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacjawypozyczalnia', '0016_alter_klient_options_wypozyczenie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
